spring:
  profiles: dev
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/hspro?allowMultiQueries=true
    username: ENC(ZdHsOWbxnOauHVkbn58PiQ==)
    password: ENC(kwh9g2AIM2uprH414s7gmosLLjIfoXaG)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  session:
    store-type: jdbc
#    jdbc.initialize-schema: always   SPRING_SESSION, SPRING_SESSION_ATTRIBUTES 테이블 자동 생성